### ISSUE TITLE
Contact Brooke (Jewish Genealogy) to discuss needs of RtR and GG

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#10]
Contact Brooke (Jewish Genealogy/Reclaim the records)

**Comment by PatReynolds** [comment]
try via Open Genealogy group

**Comment by richpomfret** [comment]
Email sent - awaiting response.

**Comment by PatReynolds** [comment]
Email sent 30/1/2017

**Comment by benwbrum** [comment]
I just sent Brooke a DM and offered to chat off-the-record about her interest and availability.

**Comment by benwbrum** [comment]
I've just heard from Brooke that she definitely will not have capacity to
work with us on the current Hanadiv funding cycle.
