### ISSUE TITLE
Review open-calls (Zooniverse) for applications

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#12]
Review application process and documents - what will be needed and when?

**Comment by PatReynolds** [comment]
The zooniverse folder now has in it the funders's sheet for Zooniverse, which has a link to the generic call-for-applications, and the questions from the current Biomedical projects open call.  

I've put the questions from the generic and specific calls into a single document - over to Ben to fill in the technical answers (the intern can do the basic who, etc., and I'll do the rest.
