### ISSUE TITLE
Finalise Rails Girls 2019 projects/application form

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#126]
Added us to the Rails girls project board.

**Comment by PatReynolds** [comment]
@richpomfret @DeniseColbert projects now up on the RG soc site: https://teams.railsgirlssummerofcode.org/projects/234-free-uk-genealogy please let me know if anything needs changing
@DeniseColbert  could you modify the GSoC sign-up form, if a sign-up form is wanted?

**Comment by DeniseColbert** [comment]
The last paragraph seems to have conflated 2 different ones? MongoDB Uni and Good First Issue

I wonder if the FutureLearn course might be a bit of an ask; 4 hours per week for 6 weeks.

Repo given is FreeREG- can we give the link to the FreeUKGEN page that lists all of our repos?

**Comment by PatReynolds** [comment]
@DeniseColbert  I have made some updates to the page projects page,could you check and make live, please.

Update from waffle to zenhub in the page needed.

Cannot find the form.
