### ISSUE TITLE
Apply for Google Impact Challenge on Safety for completing the Protection Policy with young people DEADLINE 28 June

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#128]
https://impactchallenge.withgoogle.com/safety2019/about

**Comment by richpomfret** [comment]
@PatReynolds checked the draft this morning and looks good to me. :)

**Comment by PatReynolds** [comment]
And it's in!  Had to trim/change in a couple of places due to word count.

**Comment by PatReynolds** [comment]
Winners will be announced 'early in 2020'
