### ISSUE TITLE
HLF Training Bursaries

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#17]

**Comment by carobin589** [comment]
Document available in the G-drive, Fundraising >> Other Funding. Is a currently open programme (looking for a second round of funding options in 2017). Document includes the aims of the programme, offers grants ranging from £100,000 to £750,000 (most of the awarded funding is at the higher end of this scale), and two options that I think might provide funding opportunities for us.

**Comment by DeniseColbert** [comment]
Pat to review

**Comment by PatReynolds** [comment]
@carobin589 please draft email for cultural co-operation enquiring if they are taking on new delivery partners for apprenticeships, giving our background and desire for apprentice.  @richpomfret  what level apprentice would be appropriate for an apprentice Ruby/Mongodb developer?

**Comment by PatReynolds** [comment]
@carobin589 to re-contact Cultural Cooperation @patreynolds to contact M25 group and John Sheridan (again) and @richpomfret to decide level

**Comment by PatReynolds** [comment]
HLF 'skills for the future' ran for the last time in 2016.
