### ISSUE TITLE
Zooniverse Bid/Application

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#30]
To put together/review/finalise our bid for this project.

**Comment by richpomfret** [comment]
Currently in-progress. Deadline for end of 31st Jan '17.

**Comment by carobin589** [comment]
The first draft of this is completed, so it would probably be a useful time for people to look through and add their thoughts so I can make edits as required

**Comment by PatReynolds** [comment]
Has anyone asked for the estimated % handwritten from FreeCEN, FreeREG and FreeBMD?  Handwritten would include annotations in hand on typescript or printed copy

**Comment by Captainkirkdawson** [comment]
As for FR with original PRs/ATs and BTs it is 100% handwritten. With 10% in
Latin and using a Chancery Secretary script.

For historical society documents it is 90% typed

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
