### ISSUE TITLE
Review CSi tool and contact developer

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#36]
Pat to speak to Daniel and arrnage introduction to developer.

**Comment by DeniseColbert** [comment]
Pat to chase developer

**Comment by PatReynolds** [comment]
Cf http://discovery.nationalarchives.gov.uk/details/r/C513631 as a potential first project

**Comment by PatReynolds** [comment]
Wrote 27/12

**Comment by richpomfret** [comment]
Meeting today with the developers.

**Comment by richpomfret** [comment]
For us to now finalise which project we wish to use to test this out - to prepare required sign-up/agreement text (open-data etc), to then request a new group to be set-up with Banai for us to then test and begin using. Do we go with the above first project idea? Also need to define which fields to extract data from.

**Comment by benwbrum** [comment]
We can also point a handful of existing volunteers at one of the English-language CSI projects like the NYC marriage license application indices to get their impressions of the tool.  I've just tried it, and am very impressed.

**Comment by richpomfret** [comment]
@benwbrum to email CSi developer and clarify check-box issues (which might affect FreeCen transcribing).

**Comment by benwbrum** [comment]
The CSI tool does not support checkboxes (yet), but FreeCEN already has their users type "Y" in the kinds of text entry boxes CSI _does_ support, so it may not be an issue.

**Comment by benwbrum** [comment]
Also @PatReynolds is to find census sheets and a FreeCEN volunteer to connect with CSI

**Comment by PatReynolds** [comment]
Messaged freecen Coords 7 Feb.  Will ask interested cord for images.

**Comment by PatReynolds** [comment]
Re-message coords when rootsweb is back up.

**Comment by richpomfret** [comment]
@PatReynolds It's now back (although we probably want to grab our mailing lists while it's working and move onto our own system!).

**Comment by PatReynolds** [comment]
Coords asked 13/3

**Comment by richpomfret** [comment]
We have a volunteer earmarked to now work on this. Us to get things set up for them to test.
