### ISSUE TITLE
Investigate Hivos, Article 19, Foreign Commonwealth Office and SPARC as funders

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#40]

**Comment by carobin589** [comment]
Article 19 and Hivos both appear to be campaigning rather than grant giving orgs, but I have put them on the potential partners list. SPARC and the FCO look potentially  useful, although the FCO grant programs are being changed around.

**Comment by DeniseColbert** [comment]
SPARC are interesting in view of Open Data- one to watch

**Comment by benwbrum** [comment]
This has been reviewed by @carobin589 and has been added to the fundraising spreadsheet.
