### ISSUE TITLE
Microvolunteering interface

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#41]

**Comment by PatReynolds** [comment]
@carobin589 to check potential funders

**Comment by carobin589** [comment]
Have done some research, there doesn't seem to be anything funding specific, but I have put together a doc with advice and identified some potential funders from our list

**Comment by DeniseColbert** [comment]
Clare  to explore Crowd Crafting, etc. further and we need to establish what the MV project would look like / entail

**Comment by PatReynolds** [comment]
Could use zooniverse or crowdcrafting - image with image, transcription, and question(s).
1/ Find problematic data and their images @patreynolds to clarify what data is /why problematic (then can judge if appropriate for SoC).
2/ Combine data and image (Ben has experience in this)
3/ Need to set questions up as microtasks in a workflow.
4/ put into a microvolunteering site (Ben could do zooniverse).

**Comment by PatReynolds** [comment]
1/ see story #1372 on myopic vicar

**Comment by benwbrum** [comment]
[1372](https://waffle.io/freeukgen/myopicvicar/cards/5a0b4b778a76f5001bc70250)

**Comment by benwbrum** [comment]
See the story tracking quality control microvolunteering interface at https://waffle.io/freeukgen/myopicvicar/cards/5a28206ae6c5bd001b82654c

**Comment by richpomfret** [comment]
Take this project and use ruby girls template as starting point. Ben to start putting together a doc detailing spec for interface.

**Comment by benwbrum** [comment]
The next step on this is to write the quality control microvolunteering interface work up into the sort of project description which RubyGirls and GSOC expect.

See #48
