### ISSUE TITLE
Investigate Zooniverse Project Builder text entry

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/New-Projects#43]
Zooniverse has recently added text entry tools to their Project Builder service, which allows its use for online transcription.  

We need to set up a sample project on the Zooniverse Project Builder with a handful of representative images and text data entry tasks, to see whether it can support our needs.

**Comment by benwbrum** [comment]
I've been thinking about this a bit more, and think that an excellent pilot would be to upload some census sheets and ask our users to transcribe the place names at the top of the sheets -- this would be a limited test, and would collect the data we need for the placename integration and "search nearby" improvements.

**Comment by PatReynolds** [comment]
@DeniseColbert to recruit volunteer

**Comment by richpomfret** [comment]
@benwbrum to see if Eric might be able to help or assist with this.

**Comment by benwbrum** [comment]
Open question for @PatReynolds is whether we can post images of the census pages online for the transcribers, and (if not) whether we can programmatically redact or separate parts of the images for independent transcription in order to comply with restrictions and still achieve our goals.

**Comment by benwbrum** [comment]
Emailed Eric Booker for recommendations.

**Comment by PatReynolds** [comment]
Also potential for Military injuries and deaths (http://discovery.nationalarchives.gov.uk/details/r/C513631)

**Comment by PatReynolds** [comment]
Sent @benwbrum questions for zooniverse 2/11/2018

**Comment by benwbrum** [comment]
Short answer is that our volunteers and coordinators still cannot choose or assign work.  Other aspects of Zooniverse are improving, but this is (at least for now) a blocker.

**Comment by PatReynolds** [comment]
Yes - on CSI,  coords can assign batches of images (e.g. a census piece) to an individual, or individuals can choose to work on a particular batch (which might work for smaller consular BMD records, if we have them 'by invitation only' to transcribe.  'Anyone, anywhere' might also work for BMD, with double keying to ensure quality.

**Comment by richpomfret** [comment]
Closing - shall still try out Z but CSi looks like it had better/more apt functionality for us.
