### ISSUE TITLE
Apply RailsGirls SoC

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#45]
https://railsgirlssummerofcode.org/guide/projects/

NB: can be any language, not just Rails
Will be a team of people, rather than one.

**Comment by PatReynolds** [comment]
Tasks: 

Check: has at least one open-source license (dual, OS/commercial licenses are usually ok but will be looked at on a case-by-case basis) (we will need to add the name of our license in the “license” field)

Query: who will be Primary Mentor?

Write: "features and tasks: outline how you image the students to contribute, features you’re planning to work on, issues that need help."

Write: "describe skills and experience students should bring to work on the project, e.g.
* Provide a small example or coding challenge for students to solve upfront.
* Add links to online courses or katas students should be confident with.
* Frame possible features students could work on.
       …or just ask the students to contact you for this."  
Is this 'suitable for beginners' - if so, check the box on the form

Choose: "keywords: this can mean a language, like “Python”, framework like “React”, but also specific technologies or concepts"

**Comment by PatReynolds** [comment]
Is it possible for one repository to appear in two boards (so we could have one board for the SoC project, but the issues/stories would also appear in MyopicVicar or FreeCENmigration?

**Comment by benwbrum** [comment]
Our software is licensed under the Apache 2.0 license [here](https://github.com/FreeUKGen/MyopicVicar/blob/master/LICENSE-2.0.txt)

**Comment by PatReynolds** [comment]
nb #63 #493, #515 and #561 on trac are SoC possibilities

**Comment by richpomfret** [comment]
The deadline for Rails Girls Summer of Code 2018 is January 24th, 2018 (23:59:00 UTC).

**Comment by richpomfret** [comment]
Pat to pass onto Ben/Clare to review.

**Comment by richpomfret** [comment]
@PatReynolds to send the link through.

**Comment by benwbrum** [comment]
The RailsGirls proposal to review is at https://docs.google.com/document/d/1dA_4_MHYWbt-_0MsWmL83vNPf6BY88SABzZ__NGwu3c/edit

**Comment by richpomfret** [comment]
The deadline for Rails Girls Summer of Code 2018 is January 24th, 2018 (23:59:00 UTC).
