### ISSUE TITLE
Generate new projects for using AI

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#49]
As per Ben's example relating to using AI (computer vision) for helping with detecting census forms. Can we come up with a list of such example projects for new volunteers? AI/machine learning and deep learning are areas of tech many people are looking to gain experience in..

**Comment by benwbrum** [comment]
A computer vision project for FreeCEN is detailed on [FreeCEN2 Issue 393](https://github.com/FreeUKGen/FreeCENMigration/issues/393)

**Comment by benwbrum** [comment]
Open question, probably for @PatReynolds: Can we illustrate these computer vision projects by using a handful (1-6) of images from the Census records and parish registers?  It would be a lot more compelling if we could, but I don't know about the rights situation.

**Comment by richpomfret** [comment]
Thanks Ben. @PatReynolds do we have any other potential projects after our discussions with the CSi folks?

**Comment by PatReynolds** [comment]
CSi was about machine markup of images.  The other AI project is machine learning of effective ways of searching FreeCEN data.

**Comment by PatReynolds** [comment]
[FreeCEN2 Issue 411](https://waffle.io/freeukgen/freecenmigration/cards/5a78410f8fe575001eb1dfe7) is the other AI project

**Comment by benwbrum** [comment]
Pat's story involves using a data distribution to suggest ways to narrow down their query as they enter it.

**Comment by benwbrum** [comment]
A separate story is to suggest linkages between the same individuals between different census years.  We might be able to get "gold standard" data from Oliver Duke-Williams

**Comment by benwbrum** [comment]
Another idea involves OCRing will images, running NLP for Named Entity Recognition to index them.

**Comment by benwbrum** [comment]
Similar to will images, the Catholic Record Society texts could be auto-indexed through NER.
