### ISSUE TITLE
Set up FreeCEN CSi trial

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#51]

**Comment by Captainkirkdawson** [comment]
Can I ask what CSi stands for? A google search gives me nothing but structural design software

**Comment by PatReynolds** [comment]
@Captainkirkdawson Crowd Sourced Indexing - https://csindexing.com/ I am currently setting up a trial for FreeCEN

**Comment by Captainkirkdawson** [comment]
TY

**Comment by PatReynolds** [comment]
Final first draft of instructions sent to Geoff.  Awaiting password reset so I can make him an admin and invite in a transcriber for the trial

**Comment by richpomfret** [comment]
Discussion on new csi importer tool.
