### ISSUE TITLE
SoC Student Projects Announced: April 23rd - Community Bonding Begins

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#61]
Accepted students are paired with a mentor and start planning their projects and milestones

**Comment by PatReynolds** [comment]
Timeline - https://docs.google.com/spreadsheets/d/1iQ-WlsiDM1R2BMcq-G_Qh7jry6Ew2uOQH79f7H4qLq4/edit?usp=sharing

**Comment by PatReynolds** [comment]
@patreynolds to check with RG SoC potential to raise funds for our project
