### ISSUE TITLE
Wellcome Trust Funding Application ?April 2019

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#78]
To establish a project which we can use for this application:

https://wellcome.ac.uk/news/new-fund-support-groundbreaking-open-research

**Comment by richpomfret** [comment]
First step - for Ben to email the advisory board and see what people think/suggest with regard to us creating or being part of a project for this.

**Comment by richpomfret** [comment]
Propose a letter of committment once the budget/deliverables have been ironed out. Still in discussion between Pat/Oliver.

**Comment by richpomfret** [comment]
Won't happen this year due to lack of time left. @PatReynolds to speak to Oliver with regard to university time scales.

**Comment by PatReynolds** [comment]
https://wellcome.ac.uk/funding/open-research-fund Last year closed August.

Contacted Oliver for timescales at our end, 17/11/2018

**Comment by richpomfret** [comment]
@PatReynolds to update re: Oliver's response.
