### ISSUE TITLE
Contact Catholic Records Society

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#8]
For us to contact with regard to potential funding.

**Comment by benwbrum** [comment]
I've researched the history of the organization, found their most recent couple of annual reports to get a good idea of their membership and current projects, and sent email to the general secretary.

**Comment by benwbrum** [comment]
No response from the general secretary as of 2016-10-19

**Comment by benwbrum** [comment]
James at the CRS is very interested in meeting after Christmas.  Attempting to set up a meeting on the week of January 9-13.

**Comment by richpomfret** [comment]
To reorganise for 1st week of Feb (potentially) if not before.
