### ISSUE TITLE
GSoC Application: 6 Feb 2019

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#89]
Deadline was on the 23rd Jan for '18, so presuming the same for this year. TBC.

**Comment by PatReynolds** [comment]
https://developers.google.com/open-source/gsoc/timeline gives last year's.
I have downloaded it here https://drive.google.com/file/d/0BzRDUeF70MtpeGhFT1lJYTItNWs/view?usp=sharing

So ...  announcement of GSoc 2019 is "late" (according to last year).  

We should _aim_ to have everything ready to go by the new year.
We should be prepared for a LOT of engagement mid-Feb to end-March 
We should be prepared with onboarding/engagement tasks end April to mid May
we should be prepared to mentor mid May through to mid August.

**Comment by PatReynolds** [comment]
See new timetable: https://developers.google.com/open-source/gsoc/timeline

**Comment by richpomfret** [comment]
Now complete.
