### ISSUE TITLE
Contact wellcome institute/trust

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/New-Projects#9]
To contact/arrange call for potential funding.

**Comment by benwbrum** [comment]
Email sent to Chris and Pat today.

**Comment by PatReynolds** [comment]
@benwbrum can you chase, please?

**Comment by richpomfret** [comment]
Meeting organised for today.

**Comment by richpomfret** [comment]
Following the meeting, us to send through summary of our proposal.
