### ISSUE TITLE
Groom 'Good first issue' labels

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#97]
Check 'Good first issue' is a good first issue (e.g. take off any issue that is no longer in  incoming or project backlog) and add back on where possible (e.g. needs review)

**Comment by PatReynolds** [comment]
Taken label off the two issues in progress. - @Denise can you proof the changes to the 'good first issue' page (Draft1)?
@richpomfret can you add Good first issue to anything that is not labelled, but should be?

**Comment by DeniseColbert** [comment]
Draft proofed and good to go

**Comment by PatReynolds** [comment]
Draft published 12/12/2018

**Comment by richpomfret** [comment]
Added label to a handful of issues - will look to do this as part of a weekly (or biweekly) process.

**Comment by richpomfret** [comment]
Done. Have set-up a reoccuring task to do this every sprint.
