### ISSUE TITLE
Link good first issue filtered waffle boards to Tech volunteers pages

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/New-Projects#99]
Needs #97

**Comment by richpomfret** [comment]
@DeniseColbert to add now that a pass has been done on issue 97.

**Comment by DeniseColbert** [comment]
This is done:

![image](https://user-images.githubusercontent.com/19173257/50775308-b6519780-128d-11e9-817b-e8bf32a4b474.png)

If this is ok, please close.

**Comment by Captainkirkdawson** [comment]
Would it not be much better to have these sorts of links hidden by text  or
perhaps even better hidden by a forwarding link in a separate page?


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by DeniseColbert** [comment]
That would be my preference, however I was updating links previously added by Pat. Can make this change if Pat agrees.

**Comment by richpomfret** [comment]
Closing - agreed to create new story to cover best practice for links.
